#include "hardware/pio.h"
#include "hardware/clocks.h"            // for clock_get_hz() in generated header
#include "myproject_library.pio.h"      // generated by pioasm

bool myproject_init (PIO pio, uint *p_sm, uint gpio);
